### ISSUE TITLE
v1.11.4 bug

### ISSUE THREAD

**Issue by SVG1** [SniffleMan/QuickLootRE#38]
Equipped weapons are displayed, but not on all NPCs.
For example: check the "Nenya" in Falkreath. She is in jarl's house.

Now if ("playAnimations": false) then the container animation works, if the "true" it does not work.

**Comment by SniffleMan** [comment]
Should be fixed in 1.11.5

**Comment by SVG1** [comment]
The dagger of the Nenya is still not visible through quickloot.
